modLoader="lowcodefml"
showAsResourcePack = false
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="ds_expansion"
version="1.0.0"
logoFile = "logo.png"
logoBlur = false
displayName="DS Expansion"
description='''
This add-on adds a variety of content such as new Iron Man armor, weapons, crafting materials and abilities to Satsu's iron man Addon.
'''

[[dependencies.ds_expansion]]
modId = "palladium"
mandatory = true
versionRange = "[4.4.1,)"
ordering = "NONE"
side = "BOTH"
